const ferramentas = [
    {
        name:"Canvas",
        img:"https://imgur.com/aeQAzER.png"
    },
    {
        name:"Figma",
        img:"https://imgur.com/dsW2O4a.png"
    },
    {
        name:"Github",
        img:"https://imgur.com/kl2WhUM.png"
    },
    {
        name:"Docker",
        img:"https://imgur.com/0r5oUIk.png"
    }
]
export{ferramentas}